version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_USERNAME=Bassel

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb+srv://mongo:mongo123@cluster0.8m6nu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
